=== Fides-UU/TrustSECO-Spider/JSON schemas/data_requests/output_schema.json
{
    "$schema": "http://json-schema.org/draft-04/schema#",
    "title": "TrustSECO-Spider output",
    "description": "JSON schema for the TrustSECO-Spider output",
    "type": "object",
    "properties": {
        "gh_contributor_count": {
            "type": [
                "integer",
                "null"
            ]
        },
        "gh_user_count": {
            "type": [
                "integer",
                "null"
            ]
        },
        "gh_total_download_count": {
            "type": [
                "integer",
                "null"
            ]
        },
        "gh_release_download_count": {
            "type": [
                "integer",
                "null"
            ]
        },
        "gh_yearly_commit_count": {
            "type": [
                "integer",
                "null"
            ]
        },
        "gh_repository_language": {
            "type": [
                "string",
                "null"
            ]
        },
        "gh_open_issues_count": {
            "type": [
                "integer",
                "null"
            ]
        },
        "gh_zero_response_issues_count": {
            "type": [
                "integer",
                "null"
            ]
        },
        "gh_issue_ratio": {
            "type": [
                "number",
                "null"
            ]
        },
        "gh_average_resolution_time": {
            "type": [
                "number",
                "null"
            ]
        },
        "gh_owner_stargazer_count": {
            "type": [
                "integer",
                "null"
            ]
        },
        "lib_release_frequency": {
            "type": [
                "number",
                "null"
            ]
        },
        "lib_contributor_count": {
            "type": [
                "integer",
                "null"
            ]
        },
        "lib_dependency_count": {
            "type": [
                "integer",
                "null"
            ]
        },
        "lib_dependent_count": {
            "type": [
                "integer",
                "null"
            ]
        },
        "lib_latest_release_date": {
            "type": [
                "string",
                "null"
            ]
        },
        "lib_first_release_date": {
            "type": [
                "string",
                "null"
            ]
        },
        "lib_release_count": {
            "type": [
                "integer",
                "null"
            ]
        },
        "lib_sourcerank": {
            "type": [
                "integer",
                "null"
            ]
        },
        "cve_count": {
            "type": [
                "integer",
                "null"
            ]
        },
        "cve_vulnerabilities": {
            "type": "array",
            "items": [
                {
                    "type": "object",
                    "properties": {
                        "CVE_ID": {
                            "type": "string"
                        },
                        "CVE_score": {
                            "type": [
                                "number",
                                "null"
                            ]
                        },
                        "CVE_affected_version_start_type": {
                            "type": [
                                "string",
                                "null"
                            ]
                        },
                        "CVE_affected_version_start": {
                            "type": [
                                "string",
                                "null"
                            ]
                        },
                        "CVE_affected_version_end_type": {
                            "type": [
                                "string",
                                "null"
                            ]
                        },
                        "CVE_affected_version_end": {
                            "type": [
                                "string",
                                "null"
                            ]
                        }
                    },
                    "required": [
                        "CVE_ID",
                        "CVE_score",
                        "CVE_affected_version_start_type",
                        "CVE_affected_version_start",
                        "CVE_affected_version_end_type",
                        "CVE_affected_version_end"
                    ]
                }
            ]
        },
        "cve_codes": {
            "type": "array",
            "items": [
                {
                    "type": [
                        "string"
                    ]
                }
            ]
        },
        "so_popularity": {
            "type": "object",
            "properties": {
                "month": {
                    "type": "string"
                },
                "year": {
                    "type": "string"
                },
                "popularity": {
                    "type": "number"
                }
            },
            "required": [
                "month",
                "year",
                "popularity"
            ]
        },
        "virus_ratio": {
            "type": [
                "number",
                "null"
            ]
        }
    }
}

=== Fides-UU/TrustSECO-Spider/JSON schemas/data_requests/output_example.json
{
    "gh_contributor_count": 1451,
    "gh_user_count": 1067632,
    "gh_total_download_count": 515561,
    "gh_release_download_count": 1314,
    "gh_yearly_commit_count": 2012,
    "gh_repository_language": "Python",
    "gh_open_issues_count": 1985,
    "gh_zero_response_issues_count": 297,
    "gh_issue_ratio": 0.22889760147601476,
    "gh_average_resolution_time": 27007.985,
    "gh_owner_stargazer_count": 21756,
    "lib_release_frequency": 3880212.26984127,
    "lib_contributor_count": 877,
    "lib_dependency_count": 0,
    "lib_dependent_count": 35981,
    "lib_latest_release_date": "2022-05-30T17:33:29.000Z",
    "lib_first_release_date": "2006-12-02T02:07:43.000Z",
    "lib_release_count": 126,
    "lib_sourcerank": 31,
    "cve_count": 9,
    "cve_vulnerabilities": [
        {
            "CVE_ID": "CVE-2022-29216",
            "CVE_score": null,
            "CVE_affected_version_start_type": null,
            "CVE_affected_version_start": null,
            "CVE_affected_version_end_type": "excluding",
            "CVE_affected_version_end": "2.6.4"
        },
        {
            "CVE_ID": "CVE-2021-41496",
            "CVE_score": 5.5,
            "CVE_affected_version_start_type": null,
            "CVE_affected_version_start": null,
            "CVE_affected_version_end_type": "excluding",
            "CVE_affected_version_end": "1.19.0"
        },
        {
            "CVE_ID": "CVE-2021-41495",
            "CVE_score": 7.5,
            "CVE_affected_version_start_type": null,
            "CVE_affected_version_start": null,
            "CVE_affected_version_end_type": "including",
            "CVE_affected_version_end": "1.19.0"
        },
        {
            "CVE_ID": "CVE-2021-34141",
            "CVE_score": 5.3,
            "CVE_affected_version_start_type": null,
            "CVE_affected_version_start": null,
            "CVE_affected_version_end_type": "excluding",
            "CVE_affected_version_end": "1.22.0"
        },
        {
            "CVE_ID": "CVE-2021-33430",
            "CVE_score": 7.5,
            "CVE_affected_version_start_type": "including",
            "CVE_affected_version_start": "1.9.0",
            "CVE_affected_version_end_type": "including",
            "CVE_affected_version_end": "1.9.3"
        },
        {
            "CVE_ID": "CVE-2019-6446",
            "CVE_score": 9.8,
            "CVE_affected_version_start_type": null,
            "CVE_affected_version_start": null,
            "CVE_affected_version_end_type": "including",
            "CVE_affected_version_end": "1.16.0"
        },
        {
            "CVE_ID": "CVE-2017-12852",
            "CVE_score": 7.5,
            "CVE_affected_version_start_type": null,
            "CVE_affected_version_start": null,
            "CVE_affected_version_end_type": "including",
            "CVE_affected_version_end": "1.13.1"
        },
        {
            "CVE_ID": "CVE-2014-1859",
            "CVE_score": 5.5,
            "CVE_affected_version_start_type": null,
            "CVE_affected_version_start": null,
            "CVE_affected_version_end_type": "including",
            "CVE_affected_version_end": "1.8.0"
        },
        {
            "CVE_ID": "CVE-2014-1858",
            "CVE_score": 5.5,
            "CVE_affected_version_start_type": null,
            "CVE_affected_version_start": null,
            "CVE_affected_version_end_type": "excluding",
            "CVE_affected_version_end": "1.8.1"
        }
    ],
    "cve_codes": [
        "CVE-2022-29216",
        "CVE-2021-41496",
        "CVE-2021-41495",
        "CVE-2021-34141",
        "CVE-2021-33430",
        "CVE-2019-6446",
        "CVE-2017-12852",
        "CVE-2014-1859",
        "CVE-2014-1858"
    ],
    "so_popularity": {
        "month": "5",
        "year": "2022",
        "popularity": 0.770775266501
    },
    "virus_ratio": 0.0
}
